# Generated by Django 4.0.1 on 2022-02-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_module_quiz_quiz_submissions_problem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Previous_Code',
        ),
    ]
