# Generated by Django 4.0.1 on 2022-02-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_previous_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previous_code',
            old_name='code',
            new_name='source',
        ),
    ]
