# Generated by Django 4.0.1 on 2022-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_previous_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_code',
            name='source',
            field=models.TextField(max_length=20000),
        ),
    ]
