# Generated by Django 4.0.1 on 2022-02-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_previous_code_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='default_code',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
