# Generated by Django 4.0.1 on 2022-03-16 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_problem_default_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('source', models.TextField(max_length=20000)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
