# Generated by Django 4.0.1 on 2022-03-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_problem_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_submission',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
