# Generated by Django 4.0.1 on 2022-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_problem_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_submission',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
