# Generated by Django 4.0.3 on 2022-03-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_problem_submission_testcases_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_submission',
            name='date',
        ),
        migrations.RemoveField(
            model_name='problem_submission',
            name='source',
        ),
        migrations.RemoveField(
            model_name='problem_submission',
            name='testcases_passed',
        ),
        migrations.AlterField(
            model_name='problem_submission',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Rearrange_Problem',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=8000)),
                ('input_format', models.CharField(max_length=2000)),
                ('output_format', models.CharField(max_length=2000)),
                ('input1', models.CharField(max_length=500)),
                ('output1', models.CharField(max_length=500)),
                ('input2', models.CharField(max_length=500)),
                ('output2', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
        migrations.AlterField(
            model_name='problem_submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.rearrange_problem'),
        ),
    ]
