# Generated by Django 4.0.3 on 2022-03-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_remove_problem_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_submission',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem_submission',
            name='source',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='problem_submission',
            name='testcases_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem_submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem'),
        ),
        migrations.AlterField(
            model_name='problem_submission',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Rearrange_Problem_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.rearrange_problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
