# Generated by Django 4.0.3 on 2022-03-24 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_problem_submission_date_problem_submission_source_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_Submissions',
            new_name='Quiz_Submission',
        ),
    ]
