# Generated by Django 4.0.3 on 2022-03-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_submission',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
