# Generated by Django 4.0.3 on 2022-03-31 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_problem_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Problem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.problem')),
            ],
            bases=('courses.problem',),
        ),
    ]
