# Generated by Django 4.0.3 on 2022-03-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_assignment_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment_Problem',
        ),
    ]
