# Generated by Django 4.0.3 on 2022-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_assignment_problem_default_code_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
