# Generated by Django 4.0.3 on 2022-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='endedByUser',
            field=models.BooleanField(default=False),
        ),
    ]
