# Generated by Django 4.0.3 on 2022-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_assignment_endedbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
