# Generated by Django 4.0.3 on 2022-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_assessment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_submission',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
