# Generated by Django 4.0.3 on 2022-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_quiz_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_submission',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
