# Generated by Django 4.0.3 on 2022-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_problem_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='non_editable_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='not_used',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='used',
            field=models.CharField(default='', max_length=100),
        ),
    ]
