# Generated by Django 4.0.3 on 2022-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_rearrange_problem_submission_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='non_editable_lines',
            new_name='non_editable_ends',
        ),
        migrations.AddField(
            model_name='problem',
            name='non_editable_starts',
            field=models.IntegerField(default=0),
        ),
    ]
