# Generated by Django 4.0.3 on 2022-05-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_rename_non_editable_ends_problem_non_editable_lines_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='not_used',
            new_name='dont_use',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='used',
            new_name='must_use',
        ),
    ]
