# Generated by Django 4.0.3 on 2022-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_rename_not_used_problem_dont_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_registration',
            name='batch_id',
            field=models.CharField(default='All', max_length=50),
        ),
    ]
