# Generated by Django 4.0.3 on 2022-06-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_rearrange_problem_statements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
